### ISSUE TITLE
[Question] Input csv

### ISSUE THREAD

**Issue by lee1043** [PCMDI/d3_chart#12]
@William-Hill could you please point me where I can change the input csv file? Also wondering how to set the live page for that. Thank you!

**Comment by William-Hill** [comment]
@lee1043 I haven't added that feature since it wasn't in the initial list.  The csv file is currently hard-coded.  But I'll try to add it this week.

**Comment by lee1043** [comment]
@William-Hill sounds great -- thank you for following up.

**Comment by William-Hill** [comment]
@lee1043 Upload functionality has been added.  I had to write a backend to add that functionality so I had to change the way I'm hosting the demo app.  It's now at https://pcmdi-parallel-coordinates.herokuapp.com/

It only works CSVs that are in a format similar to the test file at the moment
