### ISSUE TITLE
FYI clarification on "by variable" vs "by season"

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/d3_chart#23]
@William-Hill 
I think we've both been tripped up by these labels, so maybe we should make them more explicit by changing:
"Plot by variable" to "Plot all variables for a given season"
and
"Plot by season" to "Plot all seasons for a given variable"

When "Plot all variables for a given season" is selected the resulting radio buttons should be ... Model Generation, Region, Statistic and Season

When "Plot all seasons for a given variable" is selected the resulting radio buttons should be... Variable, Model Generation, Region, Statistic

The options for Model Generation are CMIP5 or CMIP6.  A little later we will add CMIP5 + CMIP6

**Comment by gleckler1** [comment]
@William-Hill  For the most part, this issue supersedes #21

**Comment by William-Hill** [comment]
Resolved by #28
