### ISSUE TITLE
Dynamic plot title

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/d3_chart#32]
@William-Hill  As a new plot is generated, it should include a title just above the plot that includes the options chosen for each radio button.   So, 

A “plot for all seasons of a given variable” would have a title comprised of the entries for the following:

Variable Region Statistic (ModelGeneration)

and the title for a “plot of all variable for a given season”  would include:

Season Region Statistic (ModelGeneration)

**Comment by William-Hill** [comment]
Resolved by #41
