### ISSUE TITLE
replace intro text...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/d3_chart#33]
This is a PROTOTYPE of PCMDI’s Interactive Parallel Coordinate Plot (iPCP) used to dynamically display the different mean climate statistics routinely generated with the PCMDI Metrics Package (PMP).  Each vertical axis represents an independent scalar calculation or metric.  The default displays results from each model as symbols.  **The user can highlight a given model by selecting a symbol on the plot or from the table below the plot.  This feature allows, for example, two versions of the same model to be contrasted against the backdrop of results from the multi-model ensemble (symbols).**   The current version allows the user to display CMIP 5 and 6 results as: 1) All variables for a given season, or 2) All seasons for a given variable.  The orthogonal decomposition of statistics is described in Gleckler et al., 2008 (https://doi.org/10.1029/2007JD008972).   The software design and its use is being developed at PCMDI by William Hill, Jiwoo Lee and Peter Gleckler.   Comments can be sent to gleckler1@llnl.gov.

* Please note this page is optimized for screen resolution wider than 1700 pixels.

**Comment by William-Hill** [comment]
Resolved by #38
