### ISSUE TITLE
Make text size responsive

### ISSUE THREAD

**Issue by William-Hill** [PCMDI/d3_chart#35]
Use Bulma classes to make the text responsive

**Comment by gleckler1** [comment]
@William-Hill  Text is good as is on phone and tablet but needs to be larger on big screen.  Try 1.5 or 2x larger.  This may be cause some vertical axis labels to intersect which would not be good.  And alternate or combined approach might be to make axes scales, labels and legends to be bold text... that might make text more visible

**Comment by William-Hill** [comment]
Resolved by #44
