### ISSUE TITLE
limit ModelGeneration and number of Statistics available

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/d3_chart#49]
It would be good to make the following minor modes as the site goes public

1)	Make CMIP5 the only option for ModelGeneration.   We will have an improved set of CMIP6 results available in another week or so.
2)	Reduce the number of drop down Statistics available to include only the following 6 options for now….  rms_xy,  rmsc_xy,  bias_xy,  cor_xy,  mae_xy,  rms_xyt

**Comment by William-Hill** [comment]
Resolved by #50
